# 续火群号列表
group: []

# 群聊续火内容
gp_text:
  - "续火."
  - "喵喵喵"

# 群聊续火时间表达式
gp_cron: "0 0 0 * * *"

# 续火好友列表
friend: []

# 好友续火内容
fl_text:
  - "续火"

# 好友续火时间表达式
fl_cron: "0 0 0 * * *"

# 发送间隔 单位：秒
cd: 5

# 通知全部主人
notificationsAll: false